accounts/urls.py
from django.views.generic import TemplateView

from .views import RegisterAPI, LoginAPI, ChangePasswordView
from knox import views as knox_views
from django.urls import path, include

from accounts import views
from sahash import settings

app_name="accounts"
urlpatterns = [
    path('api/register/', RegisterAPI.as_view(), name='register'),
    path('api/login/', LoginAPI.as_view(), name='login'),
    path('api/logout/', knox_views.LogoutView.as_view(), name='logout'),
    path('api/logoutall/', knox_views.LogoutAllView.as_view(), name='logoutall'),
    path('api/change-password/', ChangePasswordView.as_view(), name='change-password'),
    path('api/password_reset/', include('django_rest_passwordreset.urls', namespace='password_reset')),
    path('api/user-complain-screen-1/', views.image_upload_view),
    path('api/user-complain-screen-3/', views.save_feedback, name="save_feedback"),
    path('api/user-complain-screen-4/', views.message_view, name="Take_action"),
    path('api/register-shelter-screen-2/', views.shelter, name="shelter"),
    path('api/shelter-facilities-screen-3/', views.facilities, name="facilities"),
    path('api/shelter-facilities-screen-4/', views.billing, name="billing"),

]

sahash/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from sahash import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/add_feedback.html
<html>
    <body>
    <div style="text-align: center;"><h1 style="font-size:40px"> Feedback </h1></div>
    <form action="{% url 'accounts:save_feedback' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
            {{ form }}
        <div><button type="submit">Save</button></div>
    </form>
    </body>
</html>

templates/complain_screen_1.html
<div style="text-align: center;"> <h1>User(Complainant) Action </h1> </div>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
   {{ form.as_p }}
  <button type="submit">Complain</button>
</form>

{% if img_obj %}
  <h3>Succesfully uploaded :<br> 1. Name: {{img_obj.name}} <br>
                             2. Phone No.: {{img_obj.phone}}</h3>
  <img src="{{ img_obj.image.url}}" alt="connect" style="max-height:300px">
{% endif %}

templates/facilities_shelter_screen3.html
<html>
    <body>
    <div style="text-align: center;"><h1 style="font-size:40px"> Shelter Facilities </h1></div>
    <form action="{% url 'accounts:facilities' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
            {{ form }}
        <div><button type="submit">Save</button></div>
    </form>
    </body>
</html>

templates/facilities_shelter_screen_4.html
<html>
    <body>
    <div style="text-align: center;"><h1 style="font-size:40px"> Order/Billing </h1></div>
    <form action="{% url 'accounts:billing' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
            {{ form }}
        <div><button type="submit">Save</button></div>
    </form>
    {% if img_obj %}
  <h3>Succesfully uploaded :</h3>
  <img src="{{ img_obj.upload_bill.url}}" alt="connect" style="max-height:300px">
{% endif %}
    </body>
</html>

templates/shelter_screen2.html
<html>
    <body>
    <div style="text-align: center;"><h1 style="font-size:40px"> Shelter Facilities </h1></div>
    <form action="{% url 'accounts:shelter' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
            {{ form }}
        <div><button type="submit">Save</button></div>
    </form>
    </body>
</html>

templates/take_action.html
{% load widget_tweaks %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Take Action</title>
    <style>
h1 {text-align: center;}
p {text-align: center;}
div {text-align: center;}
</style>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>
<body>
      <form action="http://127.0.0.1:8000/api/user-complain-screen-4/" method="post" enctype="multipart/form-data">
        {% csrf_token %}
  <section class="section">
    <div class="container">
        <div style="text-align: center;"><h1 style="font-size:40px"> Take Action</h1></div>
    </div>
      <br><br>
       <div class="callout-left narrow">

<h2 style="font-size:30px">Alert!</h2>

<p>Animal from your location has not been picked. Please take an action against the Shelter Manager.<br> </p>

</div>
      <br>
      <div class="container">
      <div class="columns">
        <div class="column is-half is-offset-one-quarter">
          <div class="field">
            <div class="control">
              {% render_field form.message rows="10" placeholder="Your message" class+="textarea" %}
            </div>
          </div>
          <div class="field is-grouped">
            <div class="control">
              <button class="button is-link">Submit</button>
            </div>
            <div class="control">
              <button class="button is-link is-light">Cancel</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  </form>
</body>

</html>